//! Corpus integrity tests.
//!
//! The golden corpus gates the PRD §5 recall and precision numbers, so ground
//! truth that has drifted from its fixtures is worse than no corpus at all — it
//! moves the metric silently. These tests assert that every committed label
//! still describes the committed input.
//!
//! `labels.json` is generated by `corpus/tools/build_labels.py`. Edit
//! `spec.json` and regenerate; never hand-edit offsets.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Labels {
    project: String,
    entities: Vec<Entity>,
    #[serde(default)]
    secrets: Vec<Secret>,
    #[serde(default)]
    never_alias: Vec<String>,
    #[serde(default)]
    ignored_paths: Vec<String>,
    /// Files where zero detections are expected — every hit is a false
    /// positive counting against the PRD §5 precision target.
    #[serde(default)]
    negative_files: Vec<String>,
    entity_count: usize,
    occurrence_count: usize,
}

// Field names mirror the on-disk JSON schema and cannot be renamed to satisfy
// the lint without desynchronising the corpus format.
#[allow(clippy::struct_field_names)]
#[derive(Debug, Deserialize)]
struct Entity {
    real_name: String,
    entity_type: String,
    scope_path: String,
    occurrences: Vec<Occurrence>,
}

#[derive(Debug, Deserialize)]
struct Occurrence {
    file: String,
    byte_start: usize,
    byte_end: usize,
    line: usize,
}

#[allow(clippy::struct_field_names)]
#[derive(Debug, Deserialize)]
struct Secret {
    file: String,
    byte_start: usize,
    byte_end: usize,
    secret_type: String,
}

fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus")
        .canonicalize()
        .expect("corpus directory exists")
}

fn projects() -> Vec<(String, PathBuf, Labels)> {
    let mut out = Vec::new();
    for entry in std::fs::read_dir(corpus_root()).expect("corpus is readable") {
        let dir = entry.expect("readable entry").path();
        let labels_path = dir.join("labels.json");
        if !labels_path.is_file() {
            continue;
        }
        let raw = std::fs::read_to_string(&labels_path).expect("labels.json is readable");
        let labels: Labels =
            serde_json::from_str(&raw).unwrap_or_else(|e| panic!("{}: malformed labels.json: {e}", dir.display()));
        out.push((labels.project.clone(), dir, labels));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(!out.is_empty(), "corpus has no labelled projects");
    out
}

fn read(project: &Path, relative: &str) -> String {
    let path = project.join(relative);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// The core check: every labelled byte range must actually contain the name it
/// claims. This is what catches an edited fixture whose labels were not
/// regenerated.
#[test]
fn every_occurrence_span_contains_its_real_name() {
    for (name, dir, labels) in projects() {
        for entity in &labels.entities {
            for occ in &entity.occurrences {
                let text = read(&dir, &occ.file);
                assert!(
                    occ.byte_end <= text.len(),
                    "{name}: {} span {}..{} runs past {} ({} bytes)",
                    entity.real_name,
                    occ.byte_start,
                    occ.byte_end,
                    occ.file,
                    text.len()
                );
                let found = &text[occ.byte_start..occ.byte_end];
                assert_eq!(
                    found, entity.real_name,
                    "{name}: {}:{} claims {:?} but the bytes say {:?} — regenerate with \
                     corpus/tools/build_labels.py",
                    occ.file, occ.line, entity.real_name, found
                );
            }
        }
    }
}

#[test]
fn every_secret_span_is_in_bounds_and_non_empty() {
    for (name, dir, labels) in projects() {
        for secret in &labels.secrets {
            let text = read(&dir, &secret.file);
            assert!(
                secret.byte_start < secret.byte_end && secret.byte_end <= text.len(),
                "{name}: {} span {}..{} is invalid in {}",
                secret.secret_type,
                secret.byte_start,
                secret.byte_end,
                secret.file
            );
        }
    }
}

/// Spans must not overlap within a file. An overlap means one occurrence would
/// be counted for two entities, quietly inflating recall.
#[test]
fn occurrence_spans_do_not_overlap_within_a_file() {
    for (name, _dir, labels) in projects() {
        let mut by_file: HashMap<&str, Vec<(usize, usize, &str)>> = HashMap::new();
        for entity in &labels.entities {
            for occ in &entity.occurrences {
                by_file
                    .entry(&occ.file)
                    .or_default()
                    .push((occ.byte_start, occ.byte_end, &entity.real_name));
            }
        }
        for (file, mut spans) in by_file {
            spans.sort_unstable();
            for pair in spans.windows(2) {
                let ((_, a_end, a_name), (b_start, _, b_name)) = (pair[0], pair[1]);
                assert!(
                    b_start >= a_end,
                    "{name}: in {file}, {a_name} and {b_name} claim overlapping spans"
                );
            }
        }
    }
}

/// The identity key is `(scope_path, entity_type, real_name)` — SDD §5. Two
/// labels sharing all three are one entity and must be merged, or the corpus
/// asserts a duplicate the engine can never produce.
#[test]
fn identity_keys_are_unique_within_a_project() {
    for (name, _dir, labels) in projects() {
        let mut seen = HashSet::new();
        for entity in &labels.entities {
            let key = (&entity.scope_path, &entity.entity_type, &entity.real_name);
            assert!(
                seen.insert(key),
                "{name}: duplicate identity key {:?}/{}/{}",
                entity.scope_path,
                entity.entity_type,
                entity.real_name
            );
        }
    }
}

/// Entity types must be ones `specshield-core` can actually produce, or the
/// label is unmatchable and counts as a permanent miss.
#[test]
fn entity_types_are_known_to_the_core_model() {
    use specshield_core::EntityType;
    let known: HashSet<String> = EntityType::ALL
        .iter()
        .map(|t| format!("{t:?}").to_lowercase())
        .collect();

    // The serde representation is snake_case, which differs from Debug for the
    // two multi-word variants.
    let alias = |s: &str| match s {
        "env_var" => "envvar".to_owned(),
        "path_segment" => "pathsegment".to_owned(),
        other => other.to_owned(),
    };

    for (name, _dir, labels) in projects() {
        for entity in &labels.entities {
            assert!(
                known.contains(&alias(&entity.entity_type)),
                "{name}: unknown entity_type {:?} on {}",
                entity.entity_type,
                entity.real_name
            );
        }
    }
}

/// A name on the never-alias list that is also labelled as an entity is a
/// contradiction: it would be scored as both a required detection and a false
/// positive.
#[test]
fn never_alias_terms_are_not_also_labelled_entities() {
    for (name, _dir, labels) in projects() {
        let labelled: HashSet<&str> = labels.entities.iter().map(|e| e.real_name.as_str()).collect();
        for term in &labels.never_alias {
            assert!(
                !labelled.contains(term.as_str()),
                "{name}: {term:?} is both a labelled entity and on never_alias"
            );
        }
    }
}

#[test]
fn ignored_paths_exist_so_the_ignore_rules_are_actually_exercised() {
    for (name, dir, labels) in projects() {
        for path in &labels.ignored_paths {
            assert!(
                dir.join("input").join(path).is_file(),
                "{name}: ignored_paths lists {path}, which does not exist"
            );
        }
    }
}

#[test]
fn counts_in_the_header_match_the_body() {
    for (name, _dir, labels) in projects() {
        assert_eq!(
            labels.entity_count,
            labels.entities.len(),
            "{name}: entity_count is stale"
        );
        let occurrences: usize = labels.entities.iter().map(|e| e.occurrences.len()).sum();
        assert_eq!(
            labels.occurrence_count, occurrences,
            "{name}: occurrence_count is stale"
        );
    }
}

/// Guards the Design Review B1 case explicitly. If a future refactor collapses
/// scoped identities, this fails before the recall number moves.
#[test]
fn the_repeated_column_name_case_is_present_and_scoped() {
    let (_, _, labels) = projects()
        .into_iter()
        .find(|(name, _, _)| name == "adversarial")
        .expect("adversarial project exists");

    let customer_ids: Vec<_> = labels
        .entities
        .iter()
        .filter(|e| e.real_name == "customer_id")
        .collect();

    assert_eq!(
        customer_ids.len(),
        10,
        "expected ten distinct customer_id identities, found {}",
        customer_ids.len()
    );

    let scopes: HashSet<&String> = customer_ids.iter().map(|e| &e.scope_path).collect();
    assert_eq!(
        scopes.len(),
        10,
        "the ten customer_id identities must have ten distinct scopes"
    );
}

/// The three unrelated `Status` enums, likewise.
#[test]
fn the_repeated_enum_name_case_is_present_and_scoped() {
    let (_, _, labels) = projects()
        .into_iter()
        .find(|(name, _, _)| name == "adversarial")
        .expect("adversarial project exists");

    let scopes: HashSet<&String> = labels
        .entities
        .iter()
        .filter(|e| e.real_name == "Status")
        .map(|e| &e.scope_path)
        .collect();

    assert_eq!(scopes.len(), 3, "expected three distinctly scoped Status enums");
}

/// Cross-artifact unification (SDD §5) is the feature that makes the identity
/// graph worth having. The corpus must actually contain the case.
#[test]
fn customer_subscription_appears_in_three_formats() {
    let all = projects();
    let has = |project: &str, name: &str| {
        all.iter()
            .find(|(p, _, _)| p == project)
            .is_some_and(|(_, _, labels)| labels.entities.iter().any(|e| e.real_name == name))
    };

    assert!(has("sql-schema", "customer_subscription"), "missing the SQL table");
    assert!(
        has("openapi-billing", "CustomerSubscription"),
        "missing the OpenAPI schema"
    );
    assert!(
        has("ts-service", "CustomerSubscription"),
        "missing the TypeScript interface"
    );
}

/// Every fixture file should be reachable from some label, or it is dead weight
/// that silently contributes nothing to the metrics.
#[test]
fn every_input_file_is_either_labelled_or_explicitly_ignored() {
    for (name, dir, labels) in projects() {
        let referenced: HashSet<String> = labels
            .entities
            .iter()
            .flat_map(|e| e.occurrences.iter().map(|o| o.file.clone()))
            .chain(labels.secrets.iter().map(|s| s.file.clone()))
            .chain(labels.ignored_paths.iter().map(|p| format!("input/{p}")))
            .chain(labels.negative_files.iter().cloned())
            .collect();

        let input = dir.join("input");
        let mut unreferenced = Vec::new();
        for entry in walk(&input) {
            let relative = entry
                .strip_prefix(&dir)
                .expect("under project root")
                .to_string_lossy()
                .replace('\\', "/");
            // Config files carry no entities by design.
            if relative.ends_with(".specshieldignore") {
                continue;
            }
            if !referenced.contains(&relative) {
                unreferenced.push(relative);
            }
        }
        assert!(
            unreferenced.is_empty(),
            "{name}: fixture files contribute nothing to ground truth: {unreferenced:?}"
        );
    }
}

/// A negative fixture that accidentally contains a labelled entity is not a
/// negative fixture — it would score a legitimate detection as a false positive
/// and drag precision down for the wrong reason.
#[test]
fn negative_files_carry_no_labelled_entities() {
    for (name, _dir, labels) in projects() {
        let negative: HashSet<&str> = labels.negative_files.iter().map(String::as_str).collect();
        for entity in &labels.entities {
            for occ in &entity.occurrences {
                assert!(
                    !negative.contains(occ.file.as_str()),
                    "{name}: {} is labelled inside negative fixture {}",
                    entity.real_name,
                    occ.file
                );
            }
        }
    }
}

fn walk(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            out.extend(walk(&path));
        } else {
            out.push(path);
        }
    }
    out.sort();
    out
}
